# part of this code was generated by ChatGPT in Jan 2025

rm(list=ls())
library(MASS)
library(WeightIt)
set.seed(1988)

################
################ Generate Data
################

n <- 1000
X1 <- rnorm(n)
X2 <- rnorm(n)
W <- rbinom(n, 1, plogis(0.5 * X1 - 0.25 * X2))
Y <- 2 * W + X1 + X2 + rnorm(n)

################
################ Inverse Propensity Score Weights
################

ps_model <- glm(W ~ X1 + X2, family = binomial)
ps <- predict(ps_model, type = "response")
ips_weights <- ifelse(W == 1, 1 / ps, 1 / (1 - ps))

################
################ Covariate Balancing Weights
################

cb_weights <- weightit(W ~ X1 + X2, method = "cbps", data = data.frame(W, X1, X2))$weights

################
################ ATE Estimation
################

ate_ips <- weighted.mean(Y, weights = ips_weights)
ate_cb <- weighted.mean(Y, weights = cb_weights)

################
################ Print Results
################

cat("ATE (IPS Weights):", ate_ips, "\n")
cat("ATE (CB Weights):", ate_cb, "\n")
