# part of this code was generated by ChatGPT in Jan 2025

rm(list=ls())
library(MASS)
library(WeightIt)
set.seed(1988)

################
################ Generate Data
################

n <- 1000
X1 <- rnorm(n)
X2 <- rnorm(n)
W <- rbinom(n, 1, plogis(0.5 * X1 - 0.25 * X2))
Y <- 3 + 2 * W + X1 + X2 + rnorm(n)
data = data.frame(Y, W, X1, X2)

head(data)

################
################ Utility Functions
################

compute_weights <- function(method) {
  weightit(W ~ X1 + X2, method = method, data = data)$weights
}

compute_ate <- function(weights) {
  weighted.mean(Y[W == 1], weights = weights[W == 1]) - 
    weighted.mean(Y[W == 0], weights = weights[W == 0])
}

################
################ Generate Weights
################

ips_weights <- compute_weights("glm")
ebal_weights <- compute_weights("ebal")
cbps_weights <- compute_weights("cbps")

summary(ips_weights)
summary(ebal_weights)
summary(cbps_weights)

cor(ips_weights, ebal_weights)
cor(ips_weights, cbps_weights)
cor(cbps_weights, ebal_weights)

################
################ ATE Estimation
################

ips_ate <- compute_ate(ips_weights)
ebal_ate <- compute_ate(ebal_weights)
cbps_ate <- compute_ate(cbps_weights)

################
################ Print Results
################

cat("ATE (IPS Weights):", ips_ate, "\n")
cat("ATE (Entropy Balance Weights):", ebal_ate, "\n")
cat("ATE (CBPS Weights):", cbps_ate, "\n")
